// Frontend/src/components/Sidebar/CheckoutPage.tsx
import React, { useEffect, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { AppDispatch, RootState } from "../../app/store";
import {
  checkout,
  readCurrentOrder,
  setCurrentOrder,
} from "../../app/Stores/OrderSlice";
import { useNavigate } from "react-router-dom";
import Input from "../Generics/Input";

const CheckoutPage: React.FC = () => {
  const navigate = useNavigate();
  const dispatch = useDispatch<AppDispatch>();
  const { currentOrder, cart } = useSelector((state: RootState) => state.order);
  const { user } = useSelector((state: RootState) => state.auth);

  const [orderDetails, setOrderDetails] = useState({
    Name: currentOrder.Name,
    PhoneNumber: currentOrder.PhoneNumber || "",
    Address: currentOrder.Address || "",
  });

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    setOrderDetails((prevDetails) => ({
      ...prevDetails,
      [name]: value,
    }));
  };

  dispatch(setCurrentOrder(currentOrder));

  const handleCheckout = async () => {
    try {
      dispatch(
        setCurrentOrder({
          Address: orderDetails.Address,
          Name: orderDetails.Name,
          PhoneNumber: orderDetails.PhoneNumber,
          UserId: currentOrder.UserId,
          OrderTotal: currentOrder.OrderTotal,
          Items: currentOrder.Items,
        })
      );
      await dispatch(checkout());
      dispatch(setCurrentOrder(undefined));
      navigate("/orders");
    } catch (error) {
      console.log(error);
    }
  };

  useEffect(() => {
    if (
      !currentOrder.Name ||
      !currentOrder.Address ||
      !currentOrder.PhoneNumber
    ) {
      setOrderDetails({
        Name: user.Name || "",
        PhoneNumber: user.PhoneNumber || "",
        Address: user.Address || "",
      });
    }
  }, [currentOrder, user]);

  useEffect(() => {
    if (cart.length !== currentOrder.Items.length) {
      dispatch(readCurrentOrder());
    }
  });
  return (
    <div className="container mx-auto p-6">
      <h2 className="text-2xl font-bold mb-6">Checkout</h2>
      <div className="bg-white shadow-md rounded-lg p-6 dark:bg-gray-800">
        <form>
          <div className="mb-4">
            <label className="block text-sm font-medium ">Full Name</label>
            <Input
              type="text"
              name="Name"
              placeholder="Enter Your Name..."
              value={orderDetails.Name}
              onChange={handleInputChange}
              className="mt-1 block w-full border border-gray-300 rounded-md shadow-sm sm:text-sm"
            />
          </div>

          <div className="mb-4">
            <label className="block text-sm font-medium ">Phone Number</label>
            <Input
              type="text"
              name="PhoneNumber"
              placeholder="Enter Your Phone Number..."
              value={orderDetails.PhoneNumber}
              onChange={handleInputChange}
              className="mt-1 block w-full border border-gray-300 rounded-md shadow-sm sm:text-sm"
            />
          </div>

          <div className="mb-4">
            <label className="block text-sm font-medium ">Address</label>
            <Input
              type="text"
              name="Address"
              placeholder="Enter Your Address..."
              value={orderDetails.Address}
              onChange={handleInputChange}
              className="mt-1 block w-full border border-gray-300 rounded-md shadow-sm sm:text-sm"
            />
          </div>

          <div className="mt-6 border-t border-gray-200 pt-4">
            <h3 className="text-lg font-medium mb-4">Order Summary</h3>
            <ul className="space-y-2">
              {currentOrder.Items.map((item, index) => (
                <li key={index} className="flex justify-between ">
                  <span>
                    {item.ProductName} (x{item.Quantity})
                  </span>
                  <span>${item.Price.toFixed(2)}</span>
                </li>
              ))}
            </ul>
            <div className="flex justify-between mt-4 font-bold">
              <span>Total:</span>
              <span>${currentOrder.OrderTotal.toFixed(2)}</span>
            </div>
          </div>

          <div className="mt-6">
            <button
              type="button"
              onClick={handleCheckout}
              className="w-full bg-green-600 text-white py-3 px-4 rounded-md shadow-sm hover:bg-green-700"
            >
              Place Order
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default CheckoutPage;

// Frontend/src/components/CheckoutPage.vue
<script setup lang="ts">
import { onMounted } from "vue";
import { useOrderStore } from "../stores/OrderStore";
import { useRouter } from "vue-router";
import { useAuthStore } from "../stores/AuthStore";
import { useToast } from "vue-toastification";

const authStore = useAuthStore();
const orderStore = useOrderStore();
const router = useRouter();
const toast = useToast();

onMounted(async () => {
  await orderStore.readCurrentOrder();
  console.log(orderStore.currentOrder);
});

const confirmOrder = async () => {
  try {
    await orderStore.checkout();
    router.push(`/orders/${authStore.user.Id}`);
    toast.success("Order placed successfully!");
  } catch (error) {
    console.error("Order placement failed:", error);
    toast.error("Order placement failed. Please try again.");
  }
};
</script>

<template>
  <div
    v-if="
      orderStore.cart.length >= 1 &&
      authStore.isLoggedIn &&
      authStore.role === 'customer'
    "
    class="min-h-screen bg-gray-100 flex flex-col items-center p-4"
  >
    <div class="w-full max-w-3xl bg-white rounded-lg shadow-lg p-6">
      <h1 class="text-3xl font-bold text-center mb-4">Checkout</h1>

      <div v-if="orderStore.currentOrder" class="mb-6">
        <div class="text-lg font-semibold">Personal Details</div>
        <div class="mt-2">
          <label class="block mb-2">
            <span class="font-medium">Name:</span>
            <input
              v-model="orderStore.currentOrder.Name"
              type="text"
              class="block w-full mt-1 p-2 border rounded"
            />
          </label>
          <label class="block mb-2">
            <span class="font-medium">Phone Number:</span>
            <input
              v-model="orderStore.currentOrder.PhoneNumber"
              type="text"
              class="block w-full mt-1 p-2 border rounded"
            />
          </label>
          <label class="block mb-2">
            <span class="font-medium">Address:</span>
            <input
              v-model="orderStore.currentOrder.Address"
              type="text"
              class="block w-full mt-1 p-2 border rounded"
            />
          </label>
          <p>
            <span class="font-medium">Total Amount:</span> ${{
              orderStore.currentOrder.OrderTotal
            }}
          </p>
        </div>
      </div>

      <div v-if="orderStore.currentOrder.Items.length" class="mb-6">
        <div class="text-lg font-semibold">Order Items</div>
        <ul class="mt-2">
          <li
            v-for="item in orderStore.currentOrder.Items"
            :key="item.ProductId"
            class="flex items-center justify-between mb-4"
          >
            <img
              :src="item.ProductImage"
              alt="Product Image"
              class="w-16 h-16 rounded"
            />
            <span>{{ item.ProductName }} - Quantity: {{ item.Quantity }}</span>
            <span>${{ (item.Price * item.Quantity).toFixed(2) }}</span>
          </li>
        </ul>
      </div>

      <button
        @click="confirmOrder"
        class="w-full bg-blue-500 text-white py-2 px-4 rounded hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-opacity-50"
      >
        Confirm Order
      </button>
      <RouterLink
        to="/"
        class="w-full bg-red-500 text-white py-2 px-4 rounded hover:bg-red-600 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-opacity-50"
      >
        Cancel
      </RouterLink>
    </div>
  </div>
</template>
