// Frontend/src/views/General/Reset-Password.tsx
import React, { useState } from "react";
import { useDispatch } from "react-redux";
import { resetPassword } from "../../app/Stores/AuthSlice";
import { ResetPasswordDTO } from "../../models/AuthDtos";
import { AppDispatch } from "../../app/store";
import Input from "../../components/Generics/Input";

const ResetPassword: React.FC = () => {
  const dispatch = useDispatch<AppDispatch>();
  const [currentPassword, setCurrentPassword] = useState<string>("");
  const [newPassword, setNewPassword] = useState<string>("");
  const [confirmPassword, setConfirmPassword] = useState<string>("");

  const handleReset = async (e: React.FormEvent) => {
    e.preventDefault();

    const user: ResetPasswordDTO = {
      UserId: localStorage.getItem("UserId")!,
      CurrentPassword: currentPassword,
      NewPassword: newPassword,
      ConfirmPassword: confirmPassword,
    };
    try {
      await dispatch(resetPassword(user));
      setCurrentPassword("");
      setNewPassword("");
      setConfirmPassword("");
    } catch (e) {
      console.error("Error: ", e);
    }
  };

  return (
    <div className="container mt-14 mb-12 text-gray-900 dark:text-white">
      <h1 className="text-4xl font-bold text-center">Reset Password</h1>
      <form
        onSubmit={handleReset}
        className="max-w-md mx-auto mt-8 bg-gray-100 p-8 rounded-lg shadow-md dark:bg-gray-800/90"
      >
        <div className="mb-4">
          <label htmlFor="currentPassword" className="block ">
            Current Password
          </label>
          <Input
            type="text"
            placeholder="Enter Your Current Password"
            value={currentPassword}
            onChange={(e) => setCurrentPassword(e.target.value)}
            required
          />
        </div>
        <div className="mb-4">
          <label htmlFor="newPassword" className="block">
            New Password
          </label>
          <Input
            type="password"
            placeholder="Enter your New Password"
            value={newPassword}
            onChange={(e) => setNewPassword(e.target.value)}
            required
          />
        </div>
        <div className="mb-4">
          <label htmlFor="confirmPassword" className="block">
            Confirm Password
          </label>
          <Input
            type="password"
            placeholder="PleaseConfirm Password"
            value={confirmPassword}
            onChange={(e) => setConfirmPassword(e.target.value)}
            required
          />
        </div>
        <button
          type="submit"
          className="w-full bg-primary text-white py-3  rounded-lg"
        >
          Save
        </button>
      </form>
    </div>
  );
};

export default ResetPassword;

// Frontend/src/views/Auth/ResetPassword.vue
<script lang="ts" setup>
import { ref } from "vue";
import { useAuthStore } from "../../stores/AuthStore";
import { useToast } from "vue-toastification";
import { ResetPasswordDTO } from "../../models/AuthDtos";

const authStore = useAuthStore();
const toast = useToast();
const errorMessage = ref<string | null>(null);

const createResetPasswordDTO = (): ResetPasswordDTO => ({
  UserId: authStore.user.id,
  CurrentPassword: "",
  NewPassword: "",
  ConfirmPassword: "",
});

const user = ref<ResetPasswordDTO>(createResetPasswordDTO());

const resetPassword = async () => {
  try {
    await authStore.resetPassword(user.value);
    user.value = createResetPasswordDTO();
    toast.success("Password has been reset");
  } catch (error: any) {
    errorMessage.value = error.message;
    console.error("Error resetting the password", error);
  }
};
</script>

<template>
  <div class="flex justify-center items-center min-h-screen bg-gray-100">
    <div class="bg-white p-8 rounded-lg shadow-md w-full max-w-md">
      <h2 class="text-2xl font-semibold mb-6">Reset Password</h2>
      <form @submit.prevent="resetPassword">
        <div class="mb-4">
          <label for="currentPassword" class="block text-gray-700"
            >Current Password:</label
          >
          <input
            type="password"
            id="currentPassword"
            v-model="user.CurrentPassword"
            required
            class="mt-1 p-2 w-full border rounded-lg"
          />
        </div>
        <div class="mb-4">
          <label for="newPassword" class="block text-gray-700">New Password:</label>
          <input
            type="password"
            id="newPassword"
            v-model="user.NewPassword"
            required
            class="mt-1 p-2 w-full border rounded-lg"
          />
        </div>
        <div class="mb-4">
          <label for="confirmPassword" class="block text-gray-700"
            >Confirm Password:</label
          >
          <input
            type="password"
            id="confirmPassword"
            v-model="user.ConfirmPassword"
            required
            class="mt-1 p-2 w-full border rounded-lg"
          />
        </div>
        <button
          type="submit"
          class="bg-yellow-500 text-white py-2 px-4 rounded-lg w-full"
        >
          Reset Password
        </button>
      </form>
      <div v-if="errorMessage" class="text-red-500 mt-4">{{ errorMessage }}</div>
    </div>
  </div>
</template>
